version: '3.8'

services:
  postgres:
    image: postgres
    container_name: weather_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: weath3r!
    ports:
      - "5432:5432"
    volumes:
      - weather_postgres_data:/var/lib/postgresql/data
    networks:
      - weather_laravel_network

volumes:
  weather_postgres_data:

networks:
  weather_laravel_network:
    driver: bridge
